/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import passwordmanager.model.Data;
import passwordmanager.model.User;
import passwordmanager.model.DataSource;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Gaurav_Sharma
 */
public class Welcome extends javax.swing.JFrame {
private String username = null;
private Clipboard clipboard;
private StringSelection stsel;
private DataSource dataS;

    /**
     * Creates new form Welcome
     * @param user
     * @param dataSource
     */
    public Welcome(User user, DataSource dataSource) {
        initComponents();
        passwordField.setEchoChar('•');
        dataS = dataSource;
        username = user.getUsername();
        userField.setText("Welcome "+username.toUpperCase());
        clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        fetch();
        
    }
    
    
    private void fetch(){
        DefaultTableModel m = (DefaultTableModel) table.getModel();
        int rows = m.getRowCount();
                if(rows > 0){
                    for (int i = 0 ; i < rows ; i++){
                        m.removeRow(0);
                    }
                }
        List<Data> datas = dataS.queryData(username);
        if(datas == null)
            System.out.println("NO DATA");
        else
        {
            for (Iterator<Data> it = datas.iterator(); it.hasNext();) {
                Data data = it.next();
                m.addRow(new Object[] {data.getWebsite(),data.getEmail(),data.getUsername(),data.getPhone()});
            }} 
    }
    
    
    private Welcome() {
        System.out.println("Cannot open this class directly, open from Connect.class");
        throw new UnsupportedOperationException("Not supported yet.");//To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userField = new javax.swing.JLabel();
        tab1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        websiteField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ADD = new javax.swing.JButton();
        UPDATE = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        FETCH = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userField.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        userField.setForeground(new java.awt.Color(255, 255, 255));
        userField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 650, 19));

        table.setBackground(new java.awt.Color(51, 51, 51));
        table.setForeground(new java.awt.Color(255, 255, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Website", "Email", "Username", "Phone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setColumnSelectionAllowed(true);
        table.getTableHeader().setReorderingAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
        }

        tab1.addTab("Saved Data", jScrollPane2);

        jPanel1.setBackground(new java.awt.Color(55, 71, 79));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Website");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");

        usernameField.setText("NULL");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");

        phoneField.setText("0");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone Number");

        ADD.setBackground(new java.awt.Color(55, 71, 79));
        ADD.setForeground(new java.awt.Color(255, 255, 255));
        ADD.setText("ADD");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });

        UPDATE.setBackground(new java.awt.Color(55, 71, 79));
        UPDATE.setForeground(new java.awt.Color(255, 255, 255));
        UPDATE.setText("UPDATE");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });

        DELETE.setBackground(new java.awt.Color(55, 71, 79));
        DELETE.setForeground(new java.awt.Color(255, 255, 255));
        DELETE.setText("DELETE");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });

        FETCH.setBackground(new java.awt.Color(55, 71, 79));
        FETCH.setForeground(new java.awt.Color(255, 255, 255));
        FETCH.setText("FETCH");
        FETCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FETCHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(websiteField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(42, 42, 42)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(passwordField))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(UPDATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DELETE)
                        .addComponent(ADD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(FETCH, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(websiteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(ADD))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(UPDATE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DELETE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(FETCH))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        tab1.addTab("Add New", jPanel1);

        getContentPane().add(tab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 64, -1, 294));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/passwordmanager/model/exit - Copy.jpg"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        jLabel6.setBackground(new java.awt.Color(52, 73, 94));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
int selected_column = table.getSelectedColumn();
int selected_row = table.getSelectedRow();
FETCH.doClick();
if(selected_column == 1){
   String email = (String)table.getValueAt(selected_row, 1);
   copy(email);
   return;
}
String website = (String)table.getValueAt(selected_row, 0);
String password = dataS.queryData(username,website);
copy(password);
    }//GEN-LAST:event_tableMouseClicked

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        // TODO add your handling code here:
        String website = websiteField.getText();
        String email = emailField.getText();
        String password = new String(passwordField.getPassword());
        String usernamelocal = usernameField.getText();
        String phone = phoneField.getText();
        if(!(website.isEmpty() || email.isEmpty() || passwordField.getPassword().length ==0)){
            if(!dataS.addData(username, email, password, website, usernamelocal, phone))
            {
                System.out.println("Error While Adding Data");
                return;
            }
            System.out.println("Added Successfully");
            JOptionPane.showMessageDialog(null, "Added Successfully");
            clear();
            fetch();
            tab1.setSelectedIndex(0);
        }else
            //System.out.println("Please fill the details");
        JOptionPane.showMessageDialog(null, "Please fill the details");
        
    }//GEN-LAST:event_ADDActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
        // TODO add your handling code here:
        String website = websiteField.getText();
        String password = new String(passwordField.getPassword());
        String usernamelocal = usernameField.getText();
        String phone = phoneField.getText();
        if(!(website.isEmpty())){
        if(!dataS.updateData(username, website, password, usernamelocal, phone))
        {
            System.out.println("Update Failed");
            editable(true);
            return;
        }
        System.out.println("Successfully Updated");
        JOptionPane.showMessageDialog(null, "Successfully Updated");
        clear();    fetch();    tab1.setSelectedIndex(0);
        }else
            System.out.println("Please enter Website");
            editable(true);
        JOptionPane.showMessageDialog(null, "Please Select a Row and press FETCH button");
    }//GEN-LAST:event_UPDATEActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        // TODO add your handling code here:
        String website = websiteField.getText();
        String email = emailField.getText();
        if((website.isEmpty() && email.isEmpty()) ){
            System.out.println("Please fill Website and Email field");
            JOptionPane.showMessageDialog(null, "Please Select a Row and press FETCH button");
        }else{
            if(!dataS.deleteData(username, website, email))
        {
            System.out.println("Delete Failed");
            editable(true);
            return;
        }
        System.out.println("Successfully Deleted");
        JOptionPane.showMessageDialog(null, "Successfully Deleted");
        editable(true);
        clear();    fetch();    tab1.setSelectedIndex(0);
        }
            
    }//GEN-LAST:event_DELETEActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        username = null;
        copy("");
        stsel = null;
        dataS = null;
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void FETCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FETCHActionPerformed
        // TODO add your handling code here:
        DefaultTableModel m =(DefaultTableModel) table.getModel();
        if(table.getSelectedRow() < 0){
            System.out.println("Please Select a Row to get Values");
            JOptionPane.showMessageDialog(null, "Please Select a Row and press FETCH button");
        }else{
            String website = (String) m.getValueAt(table.getSelectedRow(), 0);
            String email = (String) m.getValueAt(table.getSelectedRow(),1);
            Data data = new Data();
            if(!(website == "" && email == "")){
                data = dataS.query(username, website, email);
                editable(false);
                emailField.setText(data.getEmail());
                websiteField.setText(data.getWebsite());
                passwordField.setText(data.getPassword());
                usernameField.setText(data.getUsername());
                phoneField.setText(data.getPhone());
            }
        }
        
    }//GEN-LAST:event_FETCHActionPerformed

    
    private void copy(String data){
    StringBuilder sbf = new StringBuilder();
    sbf.append(data);
    stsel = new StringSelection(sbf.toString());
    clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
    clipboard.setContents(stsel, stsel);
    }
    
    private void clear(){
    websiteField.setText("");
    emailField.setText("");
    passwordField.setText("");
    usernameField.setText("");
    phoneField.setText("");
    }
    
    public void editable(boolean value){
        websiteField.setEditable(value);
        emailField.setEditable(value);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JButton DELETE;
    private javax.swing.JButton FETCH;
    private javax.swing.JButton UPDATE;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTabbedPane tab1;
    private javax.swing.JTable table;
    private javax.swing.JLabel userField;
    private javax.swing.JTextField usernameField;
    private javax.swing.JTextField websiteField;
    // End of variables declaration//GEN-END:variables
}
